# Generated by Django 3.2.9 on 2021-11-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ordem_menu',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordem_menu'),
            preserve_default=False,
        ),
    ]
