# Generated by Django 3.2.9 on 2021-11-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_categoria_ordem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ordem_menu',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordem_menu'),
        ),
    ]
