# Generated by Django 3.2.9 on 2021-11-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20211105_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='informacoes',
            field=models.CharField(default='a', max_length=60, verbose_name='informacoes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='foto_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
