# Generated by Django 3.2.9 on 2021-11-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20211105_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto_topo',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
