# Generated by Django 3.2.9 on 2021-11-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_categoria_foto_topo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='informacoes',
            field=models.TextField(verbose_name='informacoes'),
        ),
    ]
